---
title: "QFish Data Tidy"
author: "Hayato Murai"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
```
# Loading and cleaning data from the QFish repository 

Line fishing harvest for Barramundi was analysed 

```{r}

barra <- read_csv("C:\\Users\\murai\\Desktop\\Github Data\\MB5370_module4_personal\\data\\export1.csv")

print(barra) # Data set is incredibly messy

```
Verify data was loaded correctly

# Cleaning data
Data is being read as characters, so need to convert to numeric 
```{r}
str(barra)

barra <- barra |> mutate_at(c('Days', 'Kilograms', 'CalendarYear'), as.numeric) #This also solves the problem of NA variations

str(barra)

```

Need to remove N/A values from dataset

```{r}

is.na(barra) #checking to see if R can read any NA values in the data set

```
NA values are read correctly 

```{r}

barra <- drop_na(barra) #Removing NA values in data set

print(barra) #check clean data set

```
# Now graph data using ggplot2

```{r}

ggplot(barra, aes(x=Days , y=Kilograms, color=Region))+ #Comparing catch tonnage over time
  geom_smooth(se=FALSE)+
  geom_point()+
  facet_wrap(vars(CalendarYear))
  
```






